#!/bin/bash

if [ "$#" -ne 4 -a "$#" -ne 1 ] ; then
    echo > /dev/stderr
    echo "usage: `basename $0` <name_new_dir> <CHGCAR y/n> <WAVECAR y/n> <CONTCAR y/n>" > /dev/stderr
    echo "transfer files to a new dir from current dir" > /dev/stderr
    echo > /dev/stderr
    exit
fi

outdir=$1

rm -rf $outdir
mkdir $outdir
 
#if [ ! -f $outdir ] ; then
#    echo "ERROR: new dir doesn't exist" > /dev/stderr
#    exit
#fi

cp *.pbs POSCAR POTCAR KPOINTS INCAR $outdir

if [ "$#" -eq 4 ]; then
	if [ $2 = "y" -o $2 = 1 ]; then
		cp CHGCAR $outdir
	fi
	if [ $3 = "y" -o $3 = 1 ]; then
		cp WAVECAR $outdir
	fi
	if [ $4 = "y" -o $4 = 1 ]; then
		cp CONTCAR $outdir
		cd $outdir
		rm -f POSCAR
		mv CONTCAR POSCAR
		cd ..
	fi
fi 
