#!/bin/bash

if [ "$#" -lt 1 ] ; then
    echo > /dev/stderr
    echo "usage: `basename $0` <kdirectioin>" > /dev/stderr
    echo "extract the result of kmeshtest of abinit x=1 y=2 z=3" > /dev/stderr
    echo > /dev/stderr
    exit
fi

kd=$1

nset=`grep "ndtset" *.out|head -1|awk '{print $2}'`
echo -e "ndtset = $nset"
grep "ngkpt" *.in|tail -$nset|awk -v kd=$kd '{printf "%4.0f\n",$(kd+1)}' > kmesh.dat
grep ">Total energy" *.out|awk {'printf "%12.7f\n",$6'} > E.dat
paste kmesh.dat E.dat > kmeshtest.dat
rm kmesh.dat E.dat
