#!/bin/bash

if [ "$#" -lt 1 ] ; then
    echo > /dev/stderr
    echo "usage: `basename $0` <infile> {<names>}" > /dev/stderr
    echo "    extract the coordinates from  a POSCAR, CONTCAR" > /dev/stderr
    echo "    or equivalent file to xyz format" > /dev/stderr
    echo "  use '--' to read from standard input" > /dev/stderr
    echo > /dev/stderr
    exit
fi

infile=$1 ; shift
if [ $infile = "--" ] ; then
    infile="/dev/stdin"
elif [ ! -f $infile ] ; then
    echo "ERROR: file $infile does not exist" > /dev/stderr
    exit
fi

# Daniel's fancy way of figuring out whether something is numerical or not
#        if ( $1 !~ /^[0-9]*$/ ) { ... }

names=$@
awk \
-v names="$names" \
'BEGIN{
    ntype=split(names,name);
    ntype+=5;
    for (i=1;i<=ntype;i++) if (length(name[i])==0) name[i]=sprintf("%c",64+i);
    offset=0;
}
{

    # vasp 5 format fix
    if (NR==7) {
        if ($1*1>0) {
            offset=1;
            for (i=1;i<=NF;i++) name[i]=tmp_name[i];
        } else offset=0;
    }

    # selective dynamics fix
    if (NR==7+offset) {
        if (toupper(substr($1,1,1))=="S") offset++;
    }

    if (NR==1) sysname=$0;
    if (NR==2) alat=$1;
    if (NR>=3 && NR<=5) {
        i=NR-2;
        for (j=1;j<=3;j++) h[j,i]=alat*$(j);
    }
    if (NR==6) {
        for (i=1;i<=NF;i++) tmp_name[i]=$(i);
    }
    if (NR==6+offset && $1*1>0) {
	ntype=NF;
	nattot=0;
	for (i=1;i<=ntype;i++) nat[i]=nattot+=$(i);
    }
    if (NR==7+offset) {
	if (toupper(substr($1,1,1))=="D") {
	    for (i=1;i<=nattot;i++) {
		getline;
		x=$1;  y=$2;  z=$3;
		xn[i] = h[1,1]*x + h[1,2]*y + h[1,3]*z;
		yn[i] = h[2,1]*x + h[2,2]*y + h[2,3]*z;
		zn[i] = h[3,1]*x + h[3,2]*y + h[3,3]*z;
		j=1; while (i>nat[j]) j++;
		type[i]=j;
	    }
	} else {
	    print "ERROR: non-direct coordinates not supported yet";
            nattot=0;
	    exit;
	}
    }
}
END{
    if (nattot<=0) exit;
    print nattot;
    print sysname;
    for (i=1;i<=nattot;i++) printf("%-3s  %15.8f  %15.8f  %15.8f  %d\n",
				   name[type[i]], xn[i], yn[i], zn[i], i);
}' $infile
