#!/bin/sh

if [ "$#" -ne 1 -a "$#" -ne 2 ] ; then
    echo "usage: `basename $0` <OUTCAR_file> [<nsteps>]" > /dev/stderr
    echo "  extracts energies and maximum forces from OUTCAR" > /dev/stderr
    exit
fi

outcar=$1
if [ ! -f $outcar ] ; then
    echo "ERROR: file $outcar does not exist" > /dev/stderr
    exit
fi
nsteps=$2

#outcar=$dir/OUTCAR
#if [ ! -f $outcar ] ; then
#    echo "ERROR: file $outcar does not exist" > /dev/stderr
#    exit
#fi
#oszicar=$dir/OSZICAR
#if [ ! -f $oszicar ] ; then
#    echo "ERROR: file $oszicar does not exist" > /dev/stderr
#    exit
#fi

nions=`grep "number of ions" $outcar | head -1 | awk '{print $12}'`
isw=`grep "free  energy" $outcar | wc | awk '{print $1}'`
if [ ! $isw ] ; then
    echo "ERROR: no finished iteration steps" > /dev/stderr
    exit
fi

if [ $nsteps ] ; then 
    i0=`echo $isw $nsteps | awk '{d=$1-$2+1; print (d>0?d:1)}'`
else
    i0=1
fi

echo "# 1st col: iteration"
echo "# 2nd col: number of SCF cycles"
echo "# 3rd col: free energy (eV)"
echo "# 4th col: energy without entropy (eV)"
echo "# 5th col: change in total energy (eV)"
echo "# 6th col: maximum force (meV/A)"
echo "# 7th-9th col: maximum force in x,y,z (meV/A)"
echo "# 10th col: id of atom with maximum force"
echo "# 11th col: average absolute force (meV/A)"
echo "# 12th col: maximum force from vasp (meV/A) (for vca)"

Eold=0
for ((i=$i0;i<=$isw;i++)) ; do

    ii=`echo $i | awk '{printf("%3d",$1)}'`

    E=`grep "energy  without entropy" $outcar \
           | head -$i | tail -1 | awk '{printf("%14.6f\n",$7)}'`
    F=`grep "free  energy" $outcar \
           | head -$i | tail -1 | awk '{printf("%14.6f\n",$5)}'`
    dE=`echo $E $Eold | awk '{printf("%14.6f\n",$1-$2)}'`
    Eold=$E
    str=`echo $i | awk '{printf("Iteration  %3d(",$1)}'`
    nscf=`grep "$str" $outcar | tail -1 | awk '{printf("%3d",$4)}'`
    fmax=`grep -m$i -A\`expr $nions + 1\` TOTAL-FORCE $outcar \
          | tail -$nions \
          | awk '{
              fx=1e3*$4; fy=1e3*$5; fz=1e3*$6;
              f=sqrt(fx^2+fy^2+fz^2);
              printf("%7.1f  %7.1f %7.1f %7.1f  %3d\n", f, fx, fy, fz, NR)}' \
          | sort -rnk1 | head -1`
    favg=`grep -m$i -A\`expr $nions + 1\` TOTAL-FORCE $outcar \
          | tail -$nions \
          | awk -v nions=$nions \
                 'function abs(x) {return (x<0?-x:x)}
                 {ftot+=(abs($4)+abs($5)+abs($6))*1e3}
                 END{printf("%7.1f",ftot/nions/3)}'`



    printf "$ii  $nscf  $F $E $dE $fmax  $favg \n"

done

